### ISSUE TITLE
Update memoffset dependency

### ISSUE THREAD

**Issue by RalfJung** [ldesgoui/discord_game_sdk#101]
The latest released version of [this crates](https://crates.io/crates/discord_game_sdk_mock) still depends on memoffset 0.3. That version of memoffset has been yanked from crates.io because of soundness bugs. Would be great if you could update to the latest version 0.5. :)

**Comment by ldesgoui** [comment]
Hello Ralf,

Thanks for the issue, however that crate is not being used or developed.
Now that I think about it, I should just yank all versions.

Bests
