### ISSUE TITLE
Type ambiguity on sdk 1.0.0 & rustc 1.45.0-nightly

### ISSUE THREAD

**Issue by amPerl** [ldesgoui/discord_game_sdk#102]
Hey, thanks for the great work.

I recently updated the library from 1.0.0-rc.2 to 1.0.0 and refreshed my rust toolchain.

I now get a requirement for extra type definition on my callbacks.

```rust
error[E0283]: type annotations needed for `&discord_game_sdk::discord::Discord<'_, E>`
  --> client\src\discord.rs:46:58
   |
46 |                         gsdk.update_activity(&activity, |discord, result| {
   |                                                          ^^^^^^^ consider giving this closure parameter the explicit type `&discord_game_sdk::discord::Discord<'_, E>`, where the type parameter `E` is specified
   |
   = note: cannot satisfy `_: discord_game_sdk::event_handler::EventHandler`
   = note: required by `discord_game_sdk::methods::core::<impl discord_game_sdk::discord::Discord<'_, E>>::with_create_flags`
```

Usage as per docs: 
```rust
gsdk.update_activity(&activity, |discord, result| {
    if let Err(error) = result {
        eprintln!("Failed to update activity: {}", error);
    }
});
```

And `gsdk` is initialized from:
```rust
Discord::with_create_flags(discord_id, CreateFlags::NoRequireDiscord)
```

Any idea if this is from a recent discord_game_sdk change or nightly?

**Comment by ldesgoui** [comment]
I can't test in depth until tomorrow, CI tests are still passing it seems, so I don't believe there has been any changes/regressions.
Are you specifying the `EventHandler` at any point? Usually you just need to do it once, if you don't have one yet, `()` implements `EventHandler` 
```rust
    *gsdk.event_handler_mut() = Some(());
```

**Comment by amPerl** [comment]
My bad, that seems to be it, thanks! For some reason it worked without that on the previous version
