### ISSUE TITLE
achievements support

### ISSUE THREAD

**Issue by ldesgoui** [ldesgoui/discord_game_sdk#24]
feature flagged? it's not documented yet

**Comment by ldesgoui** [comment]
https://github.com/discordapp/discord-api-docs/pull/952

**Comment by Jump-Suit** [comment]
Mason is still working on it by the looks of the Pull Request, I'm already adding in the code from the documentation he wrote to prepare. 
I hope it shows the Achievements in the Discord App Client in the Store Page or the Library! :D
I'm already planning my Game's in-game UI Achievement System to tie in for this Visually.

**Comment by ldesgoui** [comment]
I'm not sure I follow? @Jump-Suit
