### ISSUE TITLE
Missing discord_game_sdk.dll after successful build

### ISSUE THREAD

**Issue by Songtronix** [ldesgoui/discord_game_sdk#32]
After successfully compiling it. I get the following runtime error:

`error: process didn't exit successfully: 'target\debug\discordtest.exe' (exit code: 0xc0000135, STATUS_DLL_NOT_FOUND)`

OS: `Windows 10`

**Comment by ldesgoui** [comment]
Hello, I believe the .dll needs to be in the current working directory when you run the process

**Comment by Songtronix** [comment]
Were should this dll be? Can't find it.

**Comment by Songtronix** [comment]
Added the .dll from the discord sdk. Now it works.
