### ISSUE TITLE
Bindgen padding errors targeting i686-pc-windows-msvc

### ISSUE THREAD

**Issue by amPerl** [ldesgoui/discord_game_sdk#63]
After adding the dependency to this crate, a normal release build targeting x86_64 results in:

```rust
error[E0063]: missing fields `__bindgen_padding_0`, `__bindgen_padding_1` in initializer of `discord_game_sdk_sys::DiscordImageHandle`
  --> C:\Users\romet\.cargo\registry\src\github.com-1ecc6299db9ec823\discord_game_sdk-1.0.0-rc.1\src\user.rs:38:21
   |
38 |         ImageHandle(sys::DiscordImageHandle {
   |                     ^^^^^^^^^^^^^^^^^^^^^^^ missing `__bindgen_padding_0`, `__bindgen_padding_1`
```

Could be fixed by the next release of bindgen, as some padding issues were dealt with in an unreleased commit.

Bindgen next release tracker issue(?):
https://github.com/rust-lang/rust-bindgen/issues/1701

(merged) bindgen pull request potentially fixing this issue:
https://github.com/rust-lang/rust-bindgen/pull/1710

**Comment by ldesgoui** [comment]
Thanks for reporting the issue, I'll take a look at it

**Comment by ldesgoui** [comment]
Actually it was my bad, I'll be releasing a 1.0.0-rc.2 with a fix in a few moments.
CI will also test i686 windows from now on.
Thanks for the report.

**Comment by ldesgoui** [comment]
`cargo update` should get you the latest version with the fix.

**Comment by amPerl** [comment]
Great! Works just fine now. Thank you for your time.
